# =============================================
# PERFIL POSTGRES — ative com:
# -Dspring.profiles.active=postgres
# ou via variável de ambiente:
# SPRING_PROFILES_ACTIVE=postgres
# =============================================

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false
