# =============================================
# PERFIL PADRÃO — roda localmente sem Docker
# usando banco H2 em memória
# =============================================

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 — acesse em http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Swagger UI — acesse em http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.application.name=task-api
