-- =============================================
-- V1__init.sql — initial baseline schema (PostgreSQL)
--
-- Mirrors the schema previously generated by Hibernate when the
-- postgres profile ran with ddl-auto=update. From now on, Flyway
-- owns the schema and Hibernate only validates it.
-- =============================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255),
    role          VARCHAR(255) NOT NULL,
    auth_provider VARCHAR(255) NOT NULL,
    provider_id   VARCHAR(255),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255) NOT NULL,
    priority    VARCHAR(255) NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP(6) NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_task_user_status   ON tasks (user_id, status);
CREATE INDEX idx_task_user_priority ON tasks (user_id, priority);
CREATE INDEX idx_task_user_due_date ON tasks (user_id, due_date, status);
CREATE INDEX idx_task_user_created  ON tasks (user_id, created_at);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    user_id    BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN NOT NULL,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_rt_user_revoked ON refresh_tokens (user_id, revoked);
CREATE INDEX idx_rt_expires_at   ON refresh_tokens (expires_at);
